### ISSUE TITLE
bellsouth telecomm numbers not supported

### ISSUE THREAD

**Issue by ghost** [binary-person/should-i-call-back#1]
BELLSOUTH TELECOMM, INC DBA SO

**Comment by binary-person** [comment]
can you give the phone number here except for the last 4 digits?

**Comment by ghost** [comment]
678-989

**Comment by binary-person** [comment]
where did the phone number come from

**Comment by Abnumality** [comment]
gainesville, georgia

**Comment by binary-person** [comment]
sorry, i meant to ask, is this phone number a home line, a spam call, or something else

**Comment by ghost** [comment]
it's a home number, i was testing it

**Comment by binary-person** [comment]
thanks for helping me add it!
